[pytest]
markers =
    auth: Authentication Security tests
    input: Input Validation tests
    api: API Security tests
    app: Application Security tests
    db: Database Security tests
    infra: Infrastructure Security tests
    code: Code Security tests
    logic: Business Logic Security tests
    critical: Critical Security tests
